project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!ignore/"
    - "!posts/template/*.qmd"
  resources: 
    - CNAME
    - assets/

execute:
  freeze: true

website:
  title: "Hidezo Suganuma"
  description: "Hidezo Suganuma's personal website"
  site-url: https://hidezosuganuma.net
  favicon: assets/img/favicon.ico
  navbar:
    right:
      - file: index.qmd
        text: Home
      - file: bio.qmd
        text: Bio
      - file: works.qmd
        text: Works
      - file: blog.qmd
        text: Blog
      - file: link.qmd
        text: Links
      - icon: twitter
        href: https://twitter.com/hiz_suganuma
      - icon: linkedin
        href: https://www.linkedin.com/in/hidezo-suganuma-540b08277/
      - icon: github
        href: https://github.com/hiz-repo
      - text: EN
        file: index-e.qmd
      - text: 日本語
        file: index.qmd
  page-footer: '©2025 Hidezo Suganuma <br>Except where otherwise noted, content on this site is licensed under <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC</a>.<br> For privacy policy and other terms, click <a href="/terms.html">here</a>.'
  twitter-card: true

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    highlight-style: github
    max-width: 840px

filters:
  - optimize-images
