project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
  resources: 
    - CNAME

website:
  title: "Hidezo Suganuma"
  site-url: https://hidezosuganuma.com
  site-path: "/"
  favicon: assets/img/favicon.ico
  navbar:
    right:
      - bio.qmd
      - publications.qmd
      - blog.qmd
      - link.qmd
      - icon: twitter
        href: https://twitter.com/hiz_suganuma
      - icon: linkedin
        href: https://www.linkedin.com/in/hidezo-suganuma-540b08277/
      - icon: github
        href: https://github.com/hiz-repo
      - text: English
        file: index-e.qmd
      - text: 日本語
        file: index.qmd
  page-footer: '© Copyright 2023 Hidezo Suganuma. <br>Except where otherwise noted, content on this site is licensed under <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">CC-BY-NC</a>.<br> For privacy policy and other terms, click <a href="/terms.html">here</a>.'
  twitter-card: true
  google-analytics: G-Q8B6LZFM4W

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
